#!/bin/bash
# Usage: generate-project-stack.sh <repo-path>
# Scans a project repo and writes .claude/docs/PROJECT_STACK.md
set -e

# Portable absolute-path resolution (realpath is not installed on macOS by default)
REPO="$(cd "${1:-.}" && pwd -P)"
OUTPUT="$REPO/.claude/docs/PROJECT_STACK.md"
DATE="$(date +%Y-%m-%d)"

lang=""
runtime=""
pkg_manager=""
key_deps=""
test_cmd=""
services=""

# ── Python (pyproject.toml) ───────────────────────────────────────────────
if [ -f "$REPO/pyproject.toml" ]; then
  lang="Python"

  # Runtime version
  py_ver=$(grep -m1 'requires-python' "$REPO/pyproject.toml" | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1)
  [ -n "$py_ver" ] && runtime="Python $py_ver"

  # Package manager
  if [ -f "$REPO/uv.lock" ]; then        pkg_manager="uv"
  elif [ -f "$REPO/poetry.lock" ]; then   pkg_manager="Poetry"
  elif [ -f "$REPO/Pipfile.lock" ]; then  pkg_manager="Pipenv"
  else                                     pkg_manager="pip"
  fi

  # PEP 621 dependencies array
  key_deps=$(awk '
    /^\[project\]/ { in_proj=1 }
    in_proj && /^dependencies\s*=/ { in_deps=1 }
    in_deps && /^\[/ && !/^\[project\]/ { in_deps=0; in_proj=0 }
    in_deps { print }
  ' "$REPO/pyproject.toml" \
    | grep -oE '"[a-zA-Z][a-zA-Z0-9_-]+"' \
    | tr -d '"' \
    | head -10 \
    | paste -sd ',' - | sed 's/,/, /g')

  # Poetry dependencies fallback
  if [ -z "$key_deps" ]; then
    key_deps=$(awk '
      /^\[tool\.poetry\.dependencies\]/ { in_deps=1; next }
      in_deps && /^\[/ { in_deps=0 }
      in_deps && /^[a-zA-Z]/ { print $1 }
    ' "$REPO/pyproject.toml" \
      | grep -iv '^python$' \
      | head -10 \
      | paste -sd ',' - | sed 's/,/, /g')
  fi

  # Test command: check pytest.ini first, then pyproject.toml [tool.pytest.ini_options]
  if [ -f "$REPO/pytest.ini" ]; then
    addopts=$(grep -m1 '^addopts' "$REPO/pytest.ini" 2>/dev/null | sed 's/^addopts\s*=\s*//')
    test_cmd="${pkg_manager} run pytest${addopts:+ $addopts}"
  elif grep -q '\[tool\.pytest' "$REPO/pyproject.toml" 2>/dev/null; then
    addopts=$(awk '/\[tool\.pytest/{p=1} p && /^addopts/{print; p=0}' "$REPO/pyproject.toml" \
      | sed 's/^addopts\s*=\s*//;s/"//g')
    test_cmd="${pkg_manager} run pytest${addopts:+ $addopts}"
  elif grep -q 'pytest' "$REPO/pyproject.toml" 2>/dev/null; then
    test_cmd="${pkg_manager} run pytest"
  fi

# ── Python (requirements.txt only) ────────────────────────────────────────
elif [ -f "$REPO/requirements.txt" ]; then
  lang="Python"
  pkg_manager="pip"
  key_deps=$(grep -v '^\s*#' "$REPO/requirements.txt" \
    | grep -v '^\s*$' \
    | sed 's/[>=<!].*//' \
    | head -10 \
    | paste -sd ',' - | sed 's/,/, /g')
  test_cmd="pytest"
fi

# ── Node / JavaScript / TypeScript ────────────────────────────────────────
if [ -f "$REPO/package.json" ]; then
  [ -z "$lang" ] && lang="Node.js"

  # Runtime version from engines field
  node_ver=$(grep -m1 '"node"' "$REPO/package.json" | grep -oE '[0-9]+(\.[0-9]+)*' | head -1)
  [ -n "$node_ver" ] && [ -z "$runtime" ] && runtime="Node.js $node_ver"

  # TypeScript detection
  if grep -q '"typescript"' "$REPO/package.json" 2>/dev/null || [ -f "$REPO/tsconfig.json" ]; then
    lang="TypeScript"
  fi

  # Package manager
  if [ -f "$REPO/bun.lockb" ] || [ -f "$REPO/bun.lock" ]; then     pkg_manager="bun"
  elif [ -f "$REPO/pnpm-lock.yaml" ]; then                          pkg_manager="pnpm"
  elif [ -f "$REPO/yarn.lock" ]; then                               pkg_manager="yarn"
  else                                                               pkg_manager="npm"
  fi

  # Test command
  raw_test=$(grep -A1 '"test"' "$REPO/package.json" 2>/dev/null | grep -v '"test"' | sed 's/.*":\s*"\([^"]*\)".*/\1/' | head -1)
  echo "$raw_test" | grep -qiv 'no test\|exit 1' && test_cmd="$pkg_manager run test"
fi

# ── Go ────────────────────────────────────────────────────────────────────
if [ -f "$REPO/go.mod" ]; then
  lang="Go"
  go_ver=$(grep -m1 '^go ' "$REPO/go.mod" | awk '{print $2}')
  [ -n "$go_ver" ] && runtime="Go $go_ver"
  pkg_manager="go modules"
  test_cmd="go test ./..."
fi

# ── Rust ──────────────────────────────────────────────────────────────────
if [ -f "$REPO/Cargo.toml" ]; then
  lang="Rust"
  pkg_manager="Cargo"
  test_cmd="cargo test"
fi

# ── Docker services ───────────────────────────────────────────────────────
for compose_file in \
  "$REPO/docker-compose.yml" \
  "$REPO/docker-compose.yaml" \
  "$REPO/compose.yml" \
  "$REPO/compose.yaml"; do
  if [ -f "$compose_file" ]; then
    services=$(grep -E '^  [a-zA-Z][a-zA-Z0-9_-]+:' "$compose_file" \
      | sed 's/\s*//; s/://' \
      | paste -sd ',' - | sed 's/,/, /g')
    break
  fi
done

# ── Write output ──────────────────────────────────────────────────────────
mkdir -p "$(dirname "$OUTPUT")"

{
  echo "# Project Stack"
  echo ""
  echo "> Auto-generated by SDD harness — do not edit manually."
  echo "> _Last updated: ${DATE}_"
  echo ""

  echo "## Language & Runtime"
  if [ -n "$runtime" ]; then
    echo "- $runtime"
  elif [ -n "$lang" ]; then
    echo "- $lang"
  else
    echo "- (not detected)"
  fi
  echo ""

  if [ -n "$pkg_manager" ]; then
    echo "## Package Manager"
    echo "- \`$pkg_manager\`"
    echo ""
  fi

  if [ -n "$key_deps" ]; then
    echo "## Key Dependencies"
    echo "- $key_deps"
    echo ""
  fi

  if [ -n "$test_cmd" ]; then
    echo "## Test Command"
    echo '```'
    echo "$test_cmd"
    echo '```'
    echo ""
  fi

  if [ -n "$services" ]; then
    echo "## Docker Services"
    echo "- $services"
    echo ""
  fi
} > "$OUTPUT"

echo "  PROJECT_STACK.md generated."
